#!/bin/bash

# Script de ayuda para deployment en Vercel
# Este script NO despliega automáticamente, solo te guía

echo "🚀 Sistema de Spa - Guía de Despliegue"
echo "======================================"
echo ""
echo "Este script te guiará en el proceso de despliegue."
echo ""
echo "📋 Checklist previo:"
echo "  ✓ Código subido a GitHub"
echo "  ✓ Cuenta en Vercel creada"
echo "  ✓ Cuenta en Neon creada"
echo ""
echo "📚 Guías disponibles:"
echo "  • Guía rápida: VERCEL_SETUP.md"
echo "  • Guía completa: DEPLOYMENT.md"
echo "  • Instalación local: INSTALLATION.md"
echo ""
echo "🔗 Links útiles:"
echo "  • Vercel Dashboard: https://vercel.com/dashboard"
echo "  • Neon Console: https://console.neon.tech"
echo "  • Google Cloud Console: https://console.cloud.google.com"
echo ""
echo "💡 Comandos útiles:"
echo ""
echo "# Generar secret para NEXTAUTH_SECRET o JWT_SECRET:"
echo "openssl rand -base64 32"
echo ""
echo "# Ver logs de Vercel (requiere vercel CLI):"
echo "vercel logs tu-proyecto.vercel.app --follow"
echo ""
echo "# Ejecutar migraciones de Prisma manualmente:"
echo "cd backend"
echo "npx prisma migrate deploy"
echo ""
echo "# Verificar estado de migraciones:"
echo "npx prisma migrate status"
echo ""
echo "======================================"
echo "Para comenzar, abre VERCEL_SETUP.md"
echo "======================================"
